//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Referee.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Referee.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both sides must have a different color..
        /// </summary>
        public static string ColorsMustBeDifferentError {
            get {
                return ResourceManager.GetString("ColorsMustBeDifferentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string CreatorName {
            get {
                return ResourceManager.GetString("CreatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Time.
        /// </summary>
        public static string EndTimeName {
            get {
                return ResourceManager.GetString("EndTimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string FieldRequiredError {
            get {
                return ResourceManager.GetString("FieldRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team {0} First Player.
        /// </summary>
        public static string FirstPlayer {
            get {
                return ResourceManager.GetString("FirstPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string IsFinishedName {
            get {
                return ResourceManager.GetString("IsFinishedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length for this field is 255 characters..
        /// </summary>
        public static string LengthMustBeBelow255 {
            get {
                return ResourceManager.GetString("LengthMustBeBelow255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string Match_EndTime_End_Time {
            get {
                return ResourceManager.GetString("Match_EndTime_End_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Match_IsFinished_Finished {
            get {
                return ResourceManager.GetString("Match_IsFinished_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string Match_StartTime_Start_Time {
            get {
                return ResourceManager.GetString("Match_StartTime_Start_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player One.
        /// </summary>
        public static string PlayerOneName {
            get {
                return ResourceManager.GetString("PlayerOneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Two.
        /// </summary>
        public static string PlayerTwoName {
            get {
                return ResourceManager.GetString("PlayerTwoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team {0} Second Player.
        /// </summary>
        public static string SecondPlayer {
            get {
                return ResourceManager.GetString("SecondPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side One Color.
        /// </summary>
        public static string SideOneColorName {
            get {
                return ResourceManager.GetString("SideOneColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Two Color.
        /// </summary>
        public static string SideTwoColorName {
            get {
                return ResourceManager.GetString("SideTwoColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTimeName {
            get {
                return ResourceManager.GetString("StartTimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string TablesLink {
            get {
                return ResourceManager.GetString("TablesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team One.
        /// </summary>
        public static string TeamOneName {
            get {
                return ResourceManager.GetString("TeamOneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Two.
        /// </summary>
        public static string TeamTwoName {
            get {
                return ResourceManager.GetString("TeamTwoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
    }
}
